version: '3'

volumes:
  shared:

services:
  jupyter:
    build: ./docker
    volumes:
      - ./notebooks:/notebooks
      - ./models:/models
      - shared:/logss
    ports:
      - "8888:8888"

  tensorboard:
    build: ./docker
    volumes:
      - shared:/logs
    ports:
      - "6006:6006"
    command: bash -c "rm -fr /logs/* && tensorboard --logdir=/logs"
