version: '3'

volumes:
  shared:

services:
  jupyter:
    build: ./docker
    volumes:
      - ./notebooks:/notebooks
      - ./models:/models
      - shared:/logs
      - ../../cristian/phi:/phi
      - ../../cristian/tensorbuilder:/tensorbuilder
      - ../../cristian/tfinterface:/tfinterface
    ports:
      - "8888:8888"
    command: bash -c "pip install -e /phi && pip install -e /tfinterface  &&  coconut-develop --jupyter notebook"

  tensorboard:
    build: ./docker
    volumes:
      - shared:/logs
    ports:
      - "6006:6006"
    command: bash -c "rm -fr /logs/* && tensorboard --logdir=/logs"
